# Generated by Django 4.2.2 on 2023-06-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='photos/banner')),
                ('banner_name', models.CharField(max_length=200)),
                ('banner_description', models.TextField(max_length=300)),
                ('offer', models.CharField(default=None, max_length=200, null=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_category.category')),
            ],
        ),
    ]
